import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/ui/components/navbar";
import Footer from '@/ui/components/footer';
import {montserrat} from '@/ui/fonts';
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";



export const metadata: Metadata = {
  title: "Grupo Eusse",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en" className="h-auto">
      <body
        className={` ${montserrat.className} antialiased min-h-screen flex flex-col bg-brand-50`}
        suppressHydrationWarning
      >
        <SessionProvider session={session}>
          <Navbar/>
          <main className="flex-1 flex flex-col">
            {children}
          </main>
          <Footer />
        </SessionProvider>
      </body>

    </html>
  );
}
